title: Proyecto
description: a jekyll theme for my project use
author: Juan Salvatierra
avatar: /logitoo.png
email: juan.salvatierra1999@gmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: juaneto99
  card: summary
logo: logo.png
social:
  name: Juan Salvatierra
  links:
    - https://twitter.com/thebest_r
    - https://www.facebook.com/juan.salvatierra.3551
    - https://github.com/ngzhio
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: es
